### ISSUE TITLE
Subtraction overflow error when deposit first time

### ISSUE THREAD

**Issue by honeybeemo** [yearn/brownie-wrapper-mix#11]
# Description
When you deposit tokens through the affiliate wrapper contract for the first time, it reverts with subtraction overflow error of safemath. Specifically, in the process of getting exact shares for deposit amount which is [`totalVaultBalance()`](https://github.com/yearn/yearn-vaults/blob/master/contracts/BaseWrapper.sol#L131) in BaseWrapper.sol, it returns slightly lower value than exact deposit amount due to the series of multiplication and division computation.

Because of this, `totalWrapperAssets` becomes lower than 0 leading to the subtraction overflow in safemath. [Check here](https://github.com/yearn/brownie-wrapper-mix/blob/master/contracts/AffiliateToken.sol#L92). It must be 0 as it is intended, so that it returns same amount of deposit.

## Test Environment
- I used same source code of AffiliateToken.sol and BaseWrapper.sol in yearn.
- I tested using hardhat mainnet fork
- I deposited 10000 DAI with `deposit(uint256)` in AffiliateToken.sol

## Expected
- It should succeed to deposit 10000 DAI and mint 10000 afyvDAI tokens.

## Actual
- It reverts with subtraction overflow error.
- Deposit amount:         `10000000000000000000000`
- totalWrapperAssets:    `9999999999999999996102`

## Proposal
- Add one more condition check to totalWrapperAssets is lower than Deposit amount. If that is true, then just set totalWrapperAssets = 0.

If this issue and proposal makes sense, I'll make pull request about this.

**Comment by BobTheBuidler** [comment]
Working on this issue here: https://github.com/yearn/brownie-wrapper-mix/pull/17
