### ISSUE TITLE
test_migrate fails on master

### ISSUE THREAD

**Issue by BobTheBuidler** [yearn/brownie-wrapper-mix#14]
test_migrate.py fails on master at first step: creating vault with releaseDelta = 1.

If I replace releaseDelta = 1 with releaseDelta = 0 for testing purposes, brownie is able to deploy the vault. However, test_migrate still fails due to vault1 and vault2 having same API version.

Full failure message below:

tests\test_affliate.py ....F

token = <Token Contract '0xf9C8Cf55f2E520B08d869df7bc76aa3d3ddDF913'>, registry = <Registry Contract '0x654f70d8442EA18904FA1AD79114f7250F7E9336'>
create_vault = <function create_vault.<locals>.create_vault at 0x000002B2A868F160>
affiliate_token = <AffiliateToken Contract '0x0702Fde4bb3e9CAAfA9d399D5D058F73A26D64BD'>, gov = <Account '0x66aB6D9362d4F35596279692F0251Db635165871'>      
rando = <Account '0x21b42413bA931038f35e7A5224FaDb065d297Ba3'>, affiliate = <Account '0x33A4622B82D4c04a53e170c638B944ce27cffce3'>

    def test_migrate(token, registry, create_vault, affiliate_token, gov, rando, affiliate):
>       vault1 = create_vault(releaseDelta=1, token=token)

tests\test_affliate.py:88:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests\conftest.py:66: in create_vault
    tx = liveRegistry.newExperimentalVault(
..\appdata\local\programs\python\python39\lib\site-packages\brownie\network\contract.py:1323: in __call__
    return fn(*args)  # type: ignore
..\appdata\local\programs\python\python39\lib\site-packages\brownie\network\contract.py:1676: in __call__
    return self.transact(*args)
..\appdata\local\programs\python\python39\lib\site-packages\brownie\network\contract.py:1550: in transact
    return tx["from"].transfer(
..\appdata\local\programs\python\python39\lib\site-packages\brownie\network\account.py:645: in transfer
    receipt._raise_if_reverted(exc)
..\appdata\local\programs\python\python39\lib\site-packages\brownie\network\transaction.py:386: in _raise_if_reverted
    self._expand_trace()
..\appdata\local\programs\python\python39\lib\site-packages\brownie\network\transaction.py:744: in _expand_trace
    self._get_trace()
..\appdata\local\programs\python\python39\lib\site-packages\brownie\network\transaction.py:618: in _get_trace
    self._reverted_trace(trace)
..\appdata\local\programs\python\python39\lib\site-packages\brownie\network\transaction.py:669: in _reverted_trace
    self._expand_trace()
..\appdata\local\programs\python\python39\lib\site-packages\brownie\network\transaction.py:800: in _expand_trace
    last_map[trace[i]["depth"]] = _get_last_map(address, sig)
..\appdata\local\programs\python\python39\lib\site-packages\brownie\network\transaction.py:1325: in _get_last_map
    contract = state._find_contract(address)
..\appdata\local\programs\python\python39\lib\site-packages\brownie\network\state.py:546: in _find_contract
    return Contract(address)
..\appdata\local\programs\python\python39\lib\site-packages\brownie\network\contract.py:944: in __init__
    _DeployedContractBase.__init__(self, address, owner)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <[AttributeError("Contract 'Vyper_contract' object has no attribute 'address'") raised in repr()] Contract object at 0x2b2a7e16a60>
address = '0x28a5b95C101df3Ded0C0d9074DB80C438774B6a9', owner = None, tx = None

    def __init__(
        self, address: str, owner: Optional[AccountsType] = None, tx: TransactionReceiptType = None
    ) -> None:
        address = _resolve_address(address)
        self.bytecode = web3.eth.get_code(address).hex()[2:]
        if not self.bytecode:
>           raise ContractNotFound(f"No contract deployed at {address}")
E           brownie.exceptions.ContractNotFound: No contract deployed at 0x28a5b95C101df3Ded0C0d9074DB80C438774B6a9

..\appdata\local\programs\python\python39\lib\site-packages\brownie\network\contract.py:750: ContractNotFound

**Comment by steffenix** [comment]
fixed https://github.com/yearn/brownie-wrapper-mix/pull/12
